---
abstract: 'Perl class for interpreting dates in Gedcom files'
author:
  - 'Eugene van der Pijll (pijll@gmx.net)'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.4211, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Gedcom-Date
provides:
  Gedcom::Date:
    file: lib/Gedcom/Date.pm
    version: '0.08'
  Gedcom::Date::Approximated:
    file: lib/Gedcom/Date/Approximated.pm
    version: '0.08'
  Gedcom::Date::Interpreted:
    file: lib/Gedcom/Date/Interpreted.pm
    version: '0.08'
  Gedcom::Date::Period:
    file: lib/Gedcom/Date/Period.pm
    version: '0.08'
  Gedcom::Date::Phrase:
    file: lib/Gedcom/Date/Phrase.pm
    version: '0.08'
  Gedcom::Date::Range:
    file: lib/Gedcom/Date/Range.pm
    version: '0.08'
  Gedcom::Date::Simple:
    file: lib/Gedcom/Date/Simple.pm
    version: '0.08'
requires:
  DateTime: '0.15'
  Params::Validate: '0'
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: '0.08'
